### PR TITLE
Fix issues #3 and #4

### LINKED ISSUE #3: Unable to de dot fields when there're dynamic field names
When event has dynamic field names, de_dot filter would unable to process new fields as "@fields" is set by old field names from previous events. Probably can use local variable instead of instance variable to fix this issue. For example,

``` ruby
    fields = event.to_hash.keys if @fields.nil?
    @logger.debug? && @logger.debug("de_dot: Act on these fields", :fields => fields)
    fields.each { |ref| rename_field(event, ref) if !(ref =~ /\./).nil? }
    filter_matched(event)
```

### LINKED ISSUE #4: de_dot adding fields
When I use the de_dot filter I am using a conditional statement that states:

<pre>
filter {
  if [type] == "BRO" {
    if [log_path] == "software" {
      de_dot {
        fields => [
          "version.major",
          "version.minor",
          "version.minor2",
          "version.minor3",
          "version.addl"
        ]
      }
    }
    if [log_path] == "x509" {
      de_dot {
        fields => [
          "certificate.version",
          "certificate.serial",
          "certificate.subject",
          "certificate.issuer",
          "certificate.exponent",
          "certificate.curve",
          "sans.dns",
          "basic_constraints.ca"
        ]
      }
    }
    if [log_path] == "intel" {
      de_dot {
        fields => [
          "seen.indicator",
          "seen.where",
          "seen.node"
        ]
      }
    }
[rest of filters]
}
</pre>

but this has the unintended consequence of adding the de_dot'd field to the record even if it doesn't have that field.  My issue is that sometimes these logs contain the fields and sometimes they don't.  But the de_dot filter is adding the field (without the dots) to every record creating nil fields, see below:

<pre>
      "version_minor2" => nil,
      "version_minor3" => nil,
        "version_addl" => nil
</pre>

Is there a way to tell the filter not to add the field.  I stumbled upon this issue because I initially tried to use the syntax:

<pre>
    if [log_path] in [ "software","intel","x509" ] {
      de_dot {
        fields => [
         .......
</pre>

But what this did is append all records in the above ref'd logs with all de_dot'd fields creating a very large amount of nil fields.

So back to the question.....Is there a way to have de_dot look for the field specified and only de_dot it if it exists, or should I do some @metadata tagging  to say if that field exists tag with a new metadata field then apply de_dot if that condition is met?

### PR DESCRIPTION
**Pull request by untergeek**
Check for the existence of a field to prevent accidentally adding an empty fieldref to events
where the `fields` directive is used.

Use a local variable instead of the instance variable to allow dynamic fields to be properly assessed.

fixes #3
fixes #4

### CODE REVIEW

File: lib/logstash/filters/de_dot.rb [hunk 1]
```diff
@@ -36,6 +36,26 @@ def register
...
   private
+  def find_fieldref_for_delete(source)
+    # In cases where fieldref may look like [a.b][c.d][e.f], we only want to delete
+    # the first level at which the dotted field appears.
+    fieldref = ''
+    @logger.debug? && @logger.debug("de_dot: source fieldref for delete", :source => source)
+    # Iterate over each level of source
+    source.delete('[').split(']').each do |ref|
+      fieldref = fieldref + '['
+      if !(ref =~ /\./).nil?
```
Comment (ph) [inline lib/logstash/filters/de_dot.rb]: This should be the same as `ref =~ /\./` ?

File: lib/logstash/filters/de_dot.rb [hunk 2]
```diff
@@ -57,9 +77,17 @@ def rename_field(event, fieldref)
...
-    @fields.each { |ref| rename_field(event, ref) if !(ref =~ /\./).nil? }
+    if @fields.nil?
+      fields = event.to_hash.keys
+    else
+      fields = @fields
+    end
+    @logger.debug? && @logger.debug("de_dot: Act on these fields", :fields => fields)
+    fields.each do |ref|
+      if event[ref]
+        rename_field(event, ref) if !(ref =~ /\./).nil?
```
Comment (ph) [inline lib/logstash/filters/de_dot.rb]: I see we are using  `if !(ref =~ /\./).nil?` in two different places we could probably wrap that into a predicate. What do you think?

``` ruby
dotted_key?(ref) or dotted?(ref), has_dot?(ref)
```

**Comment by ph** [comment]
@untergeek really minor comments address them and merge! :D
New tests seem to cover the described problems and they run locally.
